# Configuración para la simulación de eventos en el borde
endpoint: "https://fog-ingestion-<hash>-uc.a.run.app/events"  # URL de Cloud Run

# 2. LA IP DE TU CELULAR (IP Webcam)
# Si quisieras usar la webcam de la laptop, pondrías: camera_source: 0
camera_source: "http://192.168.18.46:8080/video"


send_interval_seconds: 5
retry_interval_seconds: 10
buffer_file: "./fog_buffer/events_pending.jsonl"

camera_ids:
  - "CAM-CELULAR-01"


thresholds:
  people_high: 50
  rapid_accumulation: 3
